[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.13.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

