name: server-go CI

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  CONAN_LOGIN_USERNAME_OSP: ${{ secrets.osp_conan_usr }}
  CONAN_PASSWORD_OSP: ${{ secrets.osp_conan_pwd }}
  CONAN_REVISIONS_ENABLED: 1
  CONAN_NON_INTERACTIVE: True

jobs:
  linux:
    name: Go
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2016, windows-2019]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install prerequisites
        run: |
          pip install --upgrade setuptools pip
          pip install conan
      - name: Configure libcxx for Linux
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
        if: runner.os == 'Linux'
      - name: Configure compiler.version for Windows
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.version=15 default
        if: runner.os == 'Windows'
      - name: Add Conan remote
        run: conan remote add osp https://osp-conan.azurewebsites.net/artifactory/api/conan/public --force
      - name: Install Conan deps
        run: conan install -s build_type=Release .
        env:
          CGO_LDFLAGS: '-Wl,-rpath,\$$ORIGIN/../lib'
      - name: Go build
        run: go build -v
