name: server-go CI

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  CONAN_LOGIN_USERNAME_OSP: ${{ secrets.osp_conan_usr }}
  CONAN_PASSWORD_OSP: ${{ secrets.osp_conan_pwd }}
  CONAN_REVISIONS_ENABLED: 1
  CONAN_NON_INTERACTIVE: True

jobs:
  linux:
    name: Go
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2016, widnows-2019]

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites Linux
        run: |
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan
        if: runner.os == 'Linux'
      - name: Install prerequisites Windows
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan
        if: runner.os == 'Windows'
      - name: Configure libcxx for Linux
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
        if: runner.os == 'Linux'
      - name: Add Conan remote
        run: conan remote add osp https://osp-conan.azurewebsites.net/artifactory/api/conan/public --force
      - name: Install Conan deps
        run: conan install -s build_type=Release .
      - name: Go
        run: go version
      - name: Gcc
        run: gcc --version